_BASE_: ../../Base_R50.yaml
MODEL:
  META_ARCHITECTURE: "videomt_online"
  BACKBONE:
    NAME: "VidEoMT"
    IMG_SIZE: 640
    NUM_CLASSES: 40
    HIDDEN_DIM: 768
    SEGMENTER_BLOCKS: [9,10,11]
    MODEL_NAME : "vit_base_patch14_reg4_dinov2"
    SIZE_DIVISIBILITY: 32
    NUM_OBJECT_QUERIES: 200
    DEC_LAYERS: 3
    
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.0001
  LLRD: 0.6
  WEIGHT_DECAY: 0.05
  POLY_POWER: 0.9
  WARMUP_STEPS: [500, 1000]
  MAX_ITER: 40000


INPUT:
  SAMPLING_FRAME_NUM: 5
  SAMPLING_FRAME_RANGE: 2





