_BASE_: ../../Base_R50.yaml

MODEL:
  META_ARCHITECTURE: "videomt_online"
  BACKBONE:
    NAME: "VidEoMT"
    IMG_SIZE: 640
    NUM_CLASSES: 25
    HIDDEN_DIM: 1024
    SEGMENTER_BLOCKS: [20,21,22,23]
    SIZE_DIVISIBILITY: 32
    NUM_OBJECT_QUERIES: 200
    
    
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.0001
  LLRD: 0.6
  WEIGHT_DECAY: 0.05
  POLY_POWER: 0.9
  WARMUP_STEPS: [500, 1000]
  MAX_ITER: 160000



INPUT:
  SAMPLING_FRAME_NUM: 5
  SAMPLING_FRAME_RANGE: 2
  MIN_SIZE_TEST: 544





